parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "127.0.0.1"
        port:     "3306"
        dbname:   "sportEntreAmis"
        user:     "root"
        password: "root"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation # annotation ou xml
                dir: '%kernel.project_dir%/src/Entity' # configuration du mapping
                prefix: 'App\Entity'
                alias: App