# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

index:
    path: /
    defaults: { _controller: 'App\Controller\IndexController::index' }

register:
    path: /inscription
    controller: App\Controller\RegisterController::registerAction

login:
    path: /connexion
    controller: App\Controller\LoginController::loginAction

logout:
    path: /deconnexion
    controller: App\Controller\LoginController::logoutAction

user:
    path: /user
    controller: App\Controller\UserController::indexAction

establishment:
    path: /user/etablissement
    controller: App\Controller\UserController::establishmentAction

ground:
    path: /user/terrain
    controller: App\Controller\UserController::groundAction

remove-ground:
    path: /user/suppression-terrain/{groundId}
    controller: App\Controller\UserController::removeGroundAction



