# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

index:
    path: /
    controller: App\Controller\IndexController::indexAction

search:
    path: /recherche
    controller: App\Controller\IndexController::searchAction

autocomlete:
    path: /recherche/autocomplete
    controller: App\Controller\IndexController::autocompleteAction

register:
    path: /inscription
    controller: App\Controller\RegisterController::registerAction

login:
    path: /connexion
    controller: App\Controller\LoginController::loginAction

logout:
    path: /deconnexion
    controller: App\Controller\LoginController::logoutAction

user:
    path: /user
    controller: App\Controller\UserController::indexAction

establishment:
    path: /user/etablissement
    controller: App\Controller\UserController::establishmentAction

opening-hours:
    path: /user/etablissement/horaire-ouverture
    controller: App\Controller\UserController::openingHoursAction

add-opening-hours:
    path: /user/etablissement/ajout-horaire-ouverture
    controller: App\Controller\UserController::addOpeningHoursAction

ground:
    path: /user/terrain
    controller: App\Controller\UserController::groundAction

remove-ground:
    path: /user/suppression-terrain/{groundId}
    controller: App\Controller\UserController::removeGroundAction

apply-parameter:
    path: /user/maj-parametres
    controller: App\Controller\UserController::majParamsAction

establishment-page:
    path: /user/etablissement/{establishmentHash}
    controller: App\Controller\IndexController::establishmentPageAction





