register:
    path: /inscription
    controller: App\UserBundle\Controller\RegisterController::registerAction

login:
    path: /connexion
    controller: App\UserBundle\Controller\LoginController::loginAction

logout:
    path: /deconnexion
    controller: App\UserBundle\Controller\LoginController::logoutAction